---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fafa
  labels:
    app: fafa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fafa
  template:
    metadata:
      labels:
        app: fafa
    spec:
      containers:
        - name: fafa
          image: docker.io/phengbunath/fafa:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080